### ISSUE TITLE
Ubuntu 18.04 repo package : dependency fail

### ISSUE THREAD

**Issue by s0meRandomDev** [atareao/nautilus-columns#1]
Hi,

In ubuntu 18.04 bionic beaver, `nautilus-columns` cannot be installed because most of the dependencies no longer exist in the repo, most of them have been replaced with newer version (for example,` python-imaging` > `pythin-pil` , `python-pypdf` > `python-pydf2` )

**Comment by s0meRandomDev** [comment]
My bad, just saw your github version is up-to-date. was using the wrong ppa

**Comment by sacarde** [comment]
in README I view:

sudo add-apt-repository ppa:atarea/nautilus-extensions

instead sudo add-apt-repository ppa:atareao/nautilus-extensions
