### ISSUE TITLE
Upgrade to python3

### ISSUE THREAD

**Issue by varac** [atareao/nautilus-columns#4]
Python2 EOL approaching end of 2019, please upgrade to python3 (at least the debian package from your deb repo depends on py2).

**Comment by varac** [comment]
Ping... ?

**Comment by atareao** [comment]
I'm working on it @varac .
Ubuntu 20.04 comes with a lot of work for me ;)
Thanks

**Comment by varac** [comment]
@atareao great, thanks for the plugin anyhow !

**Comment by atareao** [comment]
Fixed!!!!

**Comment by varac** [comment]
Awesome, thx !

**Comment by atareao** [comment]
@varac did you test it?

**Comment by varac** [comment]
Yes, it works !
