### ISSUE TITLE
Crash when opening Nautilus

### ISSUE THREAD

**Issue by arielaco** [atareao/nautilus-columns#6]
I'm using Ubuntu 18.04

I've been having issues trying to open nautilus for ~, it always crashes and I didn't know why. I decided to open it from the console to check out the messages and I noticed this:
```
~$ nautilus .
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
[Errno 2] No translation file found for domain: 'nautilus-columns'
Nautilus-Share-Message: 07:23:35.819: Called "net usershare info" but it failed: Failed to execute child process “net” (No such file or directory)

```
I've uninstalled nautilus-columns and now nautilus works properly again. I'm using Ubuntu in English. Not sure what may be the issue but thought of leaving this here just in case.

Take care.

**Comment by atareao** [comment]
Fixed.
